# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stopflag',
            field=models.NullBooleanField(),
        ),
    ]
