# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170618_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stopflag',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
