# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170618_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generator_object',
            field=models.TextField(null=True),
        ),
    ]
