# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_generator_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='generator_object',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
